# Imagen base
FROM node:18-alpine

# Crear directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del proyecto
COPY . .

# Exponer el puerto donde corre Express (normalmente 3000)
EXPOSE 3000

# Comando de inicio
CMD ["npm", "start"]
